# Common
spring:
  profiles:
    include:
      - domain
    active: default
---
spring:
  profiles: default

# Embedded server Setting
server:
  port: 9090

---
spring:
  profiles: production

# Embedded server Setting
server:
  port: 9090
