---
spring:
  profiles: default
  mvc:
    static-path-pattern: /resources/**

# Embedded server Setting
server:
  port: 9091


---
spring:
  profiles: production

# Embedded server Setting
server:
  port: 9091
